spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/twitter_like_db
    username: oyejide
    password: odofin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
