apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin.4@.Test_12345
            - name: MYSQL_DATABASE
              value: twitter_like_db
            - name: MYSQL_USER
              value: oyejide
            - name: MYSQL_PASSWORD
              value: P@ssw0rd!2023
          ports:
            - containerPort: 3308   # Changed container port to 3308
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3308
  type: NodePort
